### ISSUE TITLE
Feature Request: Add Wii Shop channel music

### ISSUE THREAD

**Issue by TNZGames** [deadphoenix8091/tinydb#8]
I think it would fit well in TinyDB. and plus rip the wii shop channel.

**Comment by Multimegamander** [comment]
about a month ago, I took 5 bowls before school, got to my first class (Geometry) more baked then a potato, and called my teacher a chromie homie, then took a fat nap. It was a good day that day, until 2nd period when I got called to the office for having ciggys.

**Comment by frozenLake** [comment]
The main problem with that is that the music is copywrited, and if anything will make a murder of lawyers decend from the heavens, it's that.

**Comment by legoj15** [comment]
Also, this is a database, not a front-end where users would access things so they'd never hear it

**Comment by deadphoenix8091** [comment]
Not going to happen.

Reason 1: Licensing
Reason 2: The web should be a background music free place.
